#!/bin/bash
# Pushes updated docs and API docs to github

# Install doc related stuff if needed
if [ "`which sphinx-build`" = '' ]; then
    cwd="`pwd`"
    cd /tmp
    sudo easy_install pip
    sudo pip install sphinx
    sudo pip install pygments
    cd $cwd
fi

push=$1

# Install and update Guzzle
if [ ! -d "./src" ]; then
    echo "Cloning Guzzle"
    git clone git@github.com:guzzle/guzzle src || exit 1
else
    echo "Updating Guzzle"
    cd src && git reset --hard && git pull && cd .. || exit 1
fi

# Build API docs
echo "Building API documentation"
apigen --quiet yes --source ./src/src --destination api --title Guzzle --google-analytics UA-22752917-1 --download no --source-code no &

if [ ! -d _docs ]; then
  echo 'Cloning docs from git@github.com:guzzle/guzzle-docs.git'
  git clone git@github.com:guzzle/guzzle-docs.git _docs || exit 1
else
  echo 'Updating docs'
  cd _docs && git reset --hard && git pull origin master || exit 1
  cd ..
fi

# Build documentation
cd _docs
sed -i '' 's,_build,../,g' Makefile
sed -i '' 's,$(SPHINXBUILD) -b html $(ALLSPHINXOPTS) $(BUILDDIR)/html,$(SPHINXBUILD) -a -b html $(ALLSPHINXOPTS) $(BUILDDIR),g' Makefile
echo "Building HTML documentation"
make html GA=1 &

echo "Waiting on background processes..."

wait || exit 1

cd ..

# Push to github to publish the site
if [ "$push" != "" ]; then
  echo "Pushing build to github"
  git add -A && git commit -m 'Updating' && git push origin master
fi
